<?php
function pomc_customizations_init() {
  if (arg(0) == "user" && arg(1) == "login") {
    drupal_add_js(drupal_get_path("module", "pomc_customizations") . "/js/pomc_customizations.js");
  }
}
function pomc_customizations_form_alter(&$form, &$form_state, $form_id) {
global $user;


if($form_id=='search_block_form') {
 $form['actions']['#attributes']['class'][] = 'element-invisible';
$form['search_block_form']['#attributes']['placeholder'] = t('Search');
}
if ($form_id == "user_login") {
unset($form['name']['#description']);
unset($form['pass']['#description']);
if(module_exists('ajax_register')){
$enabled_links = variable_get('ajax_register_enabled_links', array('password'));
$login_link= array(
  '#theme' => 'item_list',
  '#items' => _ajax_register_ajax_links($enabled_links),
);
}
$form['name']['#title'] = Null;
$form['pass']['#title'] = Null;
$form['name']['#attributes'] = array('placeholder' => t('Email Address'));
$form['pass']['#attributes'] = array('placeholder' => t('Password'));
//$form['links']['#markup'] = '<div class="request-link pull-right">'.$login_link['#items'][1].'</div>'; 
$form['actions']['submit']['#attributes'] = array('class' => Null);
$form['actions']['submit']['#attributes'] = array('class' => array('btn btn-large btn-primary'));
// Remove Request New Password from Block form
    $form['links']['#weight'] = 540;

}


if ($form_id == "profile2_edit_user_profile_form"){

drupal_add_js(drupal_get_path("module", "pomc_customizations") . "/js/pomc_customizations.js");
    drupal_add_js(drupal_get_path("module", "pomc_customizations") . "/js/formToWizard.js");
   drupal_add_js('jQuery(document).ready(function(){jQuery("#profile2-edit-user-profile-form").formToWizard({submitButton:"edit-submit"})});', array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));

}

}

function pomc_customizations_overlay_child_initialize() {
  // Add our custom JavaScript.
drupal_add_js(drupal_get_path("module", "pomc_customizations") . "/js/pomc_customizations.js");
}

 
 function get_individual_paste($row, $view) {
 
 $output = '';
 $title =  $view->style_plugin->rendered_fields[$view->row_index]['title'];
 $image=  $view->style_plugin->rendered_fields[$view->row_index]['field_paste_image'];
 $category =   $view->style_plugin->rendered_fields[$view->row_index]['field_category'];
  $city =   $view->style_plugin->rendered_fields[$view->row_index]['field_city'];
  $commentCount = $view->style_plugin->rendered_fields[$view->row_index]['comment_count'];
  $author = $view->style_plugin->rendered_fields[$view->row_index]['name'];
  $sharedBy = $view->style_plugin->rendered_fields[$view->row_index]['name_1'];
  $description =  $view->style_plugin->rendered_fields[$view->row_index]['body'];
  $nid=$view->style_plugin->rendered_fields[$view->row_index]['nid'];
  $like = flag_get_flag('like');
  $share = flag_get_flag('share');
  $likelink = flag_create_link('like', $nid);
  $sharelink = flag_create_link('share', $nid);
 $output .= '<div class="column clearfix pull-left"><!--<div class="curl"></div>--><div class="top"></div><div class="mid"><h2 class="title"> '.$title.'</h2><div class="pull-left">by '.$author.'<!-- url = user-name/ --></div><div class="category">in '. $category .'<!-- url = category-name/city-name/ --></div><div>' . $image . '</div><div class="paste-bar clearfix"><div class="pull-left">'.$likelink.' <span id="lightframe"> &bull; </span>'.$sharelink.'</div><div class="pull-right"><span><b class="not-liked"></b> ' . $like->get_count($nid) . ' </span><span> &bull; </span><span><b class="not-shared"></b> '.$share->get_count($nid) .'</span></div></div><p class="desc">'.$description.'</p><div class="info clearfix"><div class="pull-left">'.$commentCount.'</div></div><div class="comment"><textarea class="comment-area" rows="1" placeholder="comment"></textarea><!--<span>shift+enter new line</span>--></div></div><div class="bot"></div></div>';

return $output;
 
 }

?>
